# Generated by Django 2.0.4 on 2018-09-28 07:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GoodsTitle', models.CharField(max_length=20)),
                ('GoodsPic', models.ImageField(upload_to='goods_list')),
                ('GoodsPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('GoodsUnit', models.CharField(max_length=20)),
                ('GoodsClickRate', models.IntegerField()),
                ('GoodsIntroduce', models.CharField(max_length=200)),
                ('GoodsStorage', models.IntegerField()),
                ('GoodsContent', tinymce.models.HTMLField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeTitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='GoodsTypr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_goods.TypeInfo'),
        ),
    ]
