# Generated by Django 2.0.4 on 2018-10-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sx_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='GoodsTypr',
            new_name='GoodsType',
        ),
    ]
