# Generated by Django 2.0.4 on 2018-09-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=20)),
                ('user_emailcode', models.CharField(max_length=6)),
                ('user_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='useraddress',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sx_users.UserInfo'),
        ),
    ]
